### ISSUE TITLE
Sorting by year broken with Biblatex 3.6/Biber 2.6 (regression)

### ISSUE THREAD

**Issue by cfr42** [plk/biber#144]
Example:

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[backend=biber,style=authoryear,sorting=ynt]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\textcite{worman,geer,baez/article,wilde,knuth:ct:a,knuth:ct:b}
\printbibliography
\end{document}
```

See http://tex.stackexchange.com/questions/332978/different-ordering-scheme-for-multiple-citations-and-for-bibliography-in-biblate for a more complex example. See http://tex.stackexchange.com/a/247188/74706 for moewe's answer, which gave the expected output before I updated TeX Live to confirm the regression.

<code>authoryear</code> is not required to reproduce, but the problem is more immediately obvious when not obscured by numeric labelling.

**Comment by plk** [comment]
This is already fixed in 3.7 which is in the development folder on Sourceforge. You will need biber 2.7 also in development on Sourceforge.

**Comment by cfr42** [comment]
Good to know. I left a comment on TeX SE to this effect. Thanks.

**Comment by tmgriffiths** [comment]
The example below gives two different results depending on which version of biblatex and biber you use. The aim is the have seperate numeric style bibliographies for each chapter, sorted by appearance (`sorting=none`). With a global bibliography at the end of the `authoryear` style sorted `nyt`. 

Using the current versions from texlive (biblatex 3.6 and biber 2.6) gives a bibliography wiht the same layout, but the citations are numbered according to their appearance in the global bibliography at the end. Upgrading to the new versions, biblatex 3.7 and biber 2.7 doesn't change the output.

**biblatex 3.7 and biber 2.7**
![mwe-3 7 2 7-crop](https://cloud.githubusercontent.com/assets/4878624/19376097/79380544-9226-11e6-8830-e684e15d0cbb.png)

Roling back to and using bilatex 3.4 and biber 2.5 you get the original desired outcome of numbered citations in the chapter and an alphabetical global bibliography at the end.

**biblatex 3.4 and biber 2.5**
![mwe-3 4 2 5-crop](https://cloud.githubusercontent.com/assets/4878624/19376109/874a1442-9226-11e6-95a7-099ac5fc2841.png)



Se also my comment on [tex.se](http://tex.stackexchange.com/questions/332978/different-ordering-scheme-for-multiple-citations-and-for-bibliography-in-biblate)

### Minimal Working Example.
````
\documentclass{article}
\usepackage[%
  backend=biber,%
  style=chem-angew,%
  sorting=none,%
  sortcites,%
  refsegment=section,%
  defernumbers=true,%
  ]{biblatex}%
% The following definition is copied from authortitle.bbx/authoryear.bbx
\defbibenvironment{nolabelbib}{\list%
  {}%
  {%
    \setlength{\bibhang}{\parindent}%
    \setlength{\leftmargin}{\bibhang}%
    \setlength{\itemindent}{-\bibhang}%
    \setlength{\itemsep}{\bibitemsep}%
    \setlength{\parsep}{\bibparsep}%
  }%
}%
{\endlist}%
{\item}%

\begin{filecontents}{refs.bib}
@misc{miscA,
  author = {Author, A.},
  year = {2001},
  title = {Alpha},
}

@misc{miscB,
  author = {Buthor, B.},
  year = {2002},
  title = {Bravo},
}

@article{articleA,
  author = {Ascientist, A.},
  year = {3001},
  title = {Alpha},
  journal = {First Journal of AAAAA},
}

@article{articleB,
  author = {Bscientist, B.},
  year = {3002},
  title = {Beta},
  journal = {Second Journal of BBBBB},
}
\end{filecontents}

\addbibresource{refs.bib}

\begin{document}
  
  \section{The first}
  \cite{miscB,articleB}
  \printbibliography[heading=subbibliography, segment=\therefsegment]
  
  \section{The second}
  \cite{miscA,articleA}
  \printbibliography[heading=subbibliography, segment=\therefsegment]
  

  % \begin{refcontext}[sorting=nyt]
  %   \printbibliography[heading=bibnumbered, env=nolabelbib]
  % \end{refcontext}

  % OR...

  \newrefcontext[sorting=nyt]
  \printbibliography[heading=bibnumbered, env=nolabelbib]
  
\end{document}
````

**Comment by plk** [comment]
This situation is explained in the current PDF manual: "The default behaviour is that the data for a citation is drawn from the refcontext of the last bibliography in which it was printed. ". So, all references are by default in the refcontext `sorting=nyt/global/` which means that the citations are drawn from this refcontext, hence the incorrect numbering. The `\assignrefcontext*` macros allow you to override this default behaviour. Adding this to your example fixes the issue:

`\assignrefcontextentries[sorting=none]{miscB,articleB,miscA,articleA}`

**Comment by tmgriffiths** [comment]
Thanks! That works for my minimal example. I'm still not able to incorporate this into my large document unfortunately. But, as this is no-longer a bug issue I'll open up a question on [tex.se](https://www.tex.stackexchange.com) but what I'm after is below.

Ideally, I would like per-chapter numbered bibliographies, with a global bibliography at the end with all citations sorted authoryear. Using the `\assignrefcontext*` commands doesn't work with a `*` wildcard, like `\nocite{*}`. Without knowing what references will be cited in each chapter beforehand, or the potentially error prone colation a list of ~ 100 references per chapter might make the `\assignrefcontext*` method difficult to implement. 

I guess what I'm looking for is one of three options.

 1. `\assignrefcontextentries` being able to take a `*` wildcard.
 2. The ability to specify the sorting level, i.e `sorting-level=bysegment` in the preamble to override the default behaviour of taking the context for each reference from the last bibliography it was printed in.
 3. Some way of using `refsection=chapter` instead of `refsegment=chapter` and being able to use `\printbibliography[section=all]` at the end for a global bibliography.

**Comment by plk** [comment]
I have added a wildcard to `\assignrefcontextentries` in biblatex 3.7 DEV. So:

`\assignrefcontextentries[sorting=none]{*}`

**Comment by moewew** [comment]
I just tested @cfr42's MWE again and still get the incorrect order with Biber 2.7/`biblatex` 3.7.

The problem also occurs in 
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[backend=biber,style=authoryear,sorting=ynt,sortcites]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\textcite{worman,geer,baez/article,wilde,knuth:ct:a,knuth:ct:b}

\printbibliography
\end{document}
```

**Comment by plk** [comment]
Which platform - windows?

**Comment by moewew** [comment]
Yes indeed. 

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[backend=biber,style=authoryear,sorting=ynt,sortcites]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\textcite{worman,geer,baez/article,wilde,knuth:ct:a,knuth:ct:b}

\printbibliography
\end{document}
```

gave me

![electrabeeell](https://cloud.githubusercontent.com/assets/6755835/21271772/92336d78-c3bc-11e6-9235-012d78b98483.png)

As was noted before it seems as though only 'Wilde' is wrongly sorted.

The `--debug` log is at https://gist.github.com/moewew/6e935d07d4c6f06a1687e0d0d52ba5c5 

Seems as though the `knuth` entries get wrong years

```
[921] Internals.pm:1071> DEBUG - Sorting object for key 'knuth:ct:a' -> ["mm", "", 308, "Knuth!Donald E", "Computers Typesetting A"]
[922] Internals.pm:1071> DEBUG - Sorting object for key 'knuth:ct:b' -> ["mm", "", 310, "Knuth!Donald E", "Computers Typesetting B"]
```

**Comment by plk** [comment]
First, can you try the current 2.7 windows binaries on SF, I have updated them with a fix for the U::C issue.

**Comment by moewew** [comment]
The problem is still present with the new binaries from sourceforge. 

I also still get the incorrect years (308 and 310 instead of `1984-1` and `1986-1`) for Knuth in the `.blg`

```
[1951] Internals.pm:1071> DEBUG - Sorting object for key 'knuth:ct:a' -> ["mm", "", 308, "Knuth!Donald E", "Computers Typesetting A"]
[1952] Internals.pm:1071> DEBUG - Sorting object for key 'knuth:ct:b' -> ["mm", "", 310, "Knuth!Donald E", "Computers Typesetting B"]
```

**Comment by plk** [comment]
This is nothing to do with the original issue here, it is rather because `sortyear` was sorting as an integer whereas it should really be a literal like the other `sort*` fields. This is fixed in biblatex3.8/biber2.8.

**Comment by moewew** [comment]
Ah OK, sorry. I just got to this issue from TeX.SX and noted that it was still present for me. I will unfortunately only have time to run some tests later this week or next week. Thank you for addressing this so quickly.
