### ISSUE TITLE
How to make biber read fields with value "0"?

### ISSUE THREAD

**Issue by schoeps** [plk/biber#147]
Update: I am asking on stack exchange http://tex.stackexchange.com/questions/333927/how-to-make-biber-read-fields-with-value-0

**Comment by schoeps** [comment]
Ok, other people seem to believe that this is a bug, too:

Is there a way to force biber to read fields with value "0"? (background: I use a user-defined field citeable as boolean and it would be convenient to distinguish between the cases undefined, "0" and "1". Currently undefined and "0" are the same).

Small example using the field note:
```
\documentclass[a4paper]{article}
\usepackage{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{a2016,
  author        = {Author, A.},
  note          = {0},
  journal       = {Journal},
  title         = {Title1},
  year          = {2016}
}
@article{b2016,
  author        = {Author, B.},
  journal       = {Journal},
  title         = {Title2},
  year          = {2016}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
    \nocite{*}
    \printbibliography
\end{document}
```

**Comment by plk** [comment]
This was a bug - fixed in 2.7 which you can find in the development folder on Sourceforge. To use biber 2.7, you will need biblatex 3.7 which is also in its development folder on Sourceforge.

**Comment by schoeps** [comment]
I am afraid the bug is only partially fixed or it needs to be documented how user-defined fields must be introduced into the datamodel.

Entry `a2016` still does not show the `0`.
```
\documentclass[a4paper]{article}
\usepackage{biblatex}
\DeclareSourcemap{
	\maps[datatype=bibtex]{
		\map{
			\step[fieldsource=z]
			\step[fieldset=note, origfieldval]
		}
	}
}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{a2016,
  author        = {Author, A.},
  journal       = {Journal},
  title         = {Title1},
  year          = {2016},
  z             = {0}
}
@article{b2016,
  author        = {Author, B.},
  journal       = {Journal},
  title         = {Title2},
  year          = {2016}
}
@article{c2016,
  author        = {Author, C.},
  journal       = {Journal},
  title         = {Title3},
  year          = {2016},
  z             = {1}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
    \nocite{*}
    \printbibliography
\end{document}
```

**Comment by plk** [comment]
See the commands in section 4.5.4 (Data Model Specification). People use these all the time to create custom fields. The default data model is defined only using these commands in the file `blx-dm.def` which you can locate by doing `kpsewhich blx-dm.def` at the command line.

**Comment by schoeps** [comment]
Ok, I will check again but biber seems to make assumptions on unknown datatypes and the datatype chosen by default is maybe unfortunate if a `{0}` is discarded...

**Comment by plk** [comment]
Off the top of my head, in this case it's not the `{0}` that's discarded, it's the entire fields because it's not known to the data model.

**Comment by schoeps** [comment]
no, a `{1}` survives, see example above.

**Comment by schoeps** [comment]
Adding `z` to the datamodel seems not to help
```
\documentclass[a4paper]{article}
\usepackage{biblatex}
\DeclareDatamodelFields[type=field,datatype=literal,nullok]{z}
\DeclareDatamodelEntryfields{z}
\DeclareSourcemap{
	\maps[datatype=bibtex]{
		\map{
			\step[fieldsource=z]
			\step[fieldset=note, origfieldval]
		}
	}
}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{a2016,
  author        = {Author, A.},
  journal       = {Journal},
  title         = {Title1},
  year          = {2016},
  z             = {0}
}
@article{b2016,
  author        = {Author, B.},
  journal       = {Journal},
  title         = {Title2},
  year          = {2016}
}
@article{c2016,
  author        = {Author, C.},
  journal       = {Journal},
  title         = {Title3},
  year          = {2016},
  z             = {1}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
    \nocite{*}
    \printbibliography
\end{document}
```

> References
> [1] A. Author. “Title1”. In: Journal (2016).
> [2] B. Author. “Title2”. In: Journal (2016).
> [3] C. Author. “Title3”. In: Journal (2016). 1.


By the way: thank you for your work and the support.

**Comment by plk** [comment]
The are a couple of problems with your example. Firstly, datamodel changes can't be done in the preamble and you will have received warnings from biblatex to this effect. Also, the mapping from z->note is not really a good idea if you want to create a real custom field as mapping happens very early, before anything else. See the modified example below - you should be using a `.dbx` file and print the new field as part of an entrytype driver:

```
\documentclass[a4paper]{article}
\usepackage{filecontents}
\begin{filecontents}{\jobname.dbx}
\DeclareDatamodelFields[type=field,datatype=literal]{z}
\DeclareDatamodelEntryfields{z}
\end{filecontents}
\begin{filecontents}{\jobname.bib}
@article{a2016,
  author        = {Author, A.},
  journal       = {Journal},
  title         = {Title1},
  year          = {2016},
  z             = {0}
}
@article{b2016,
  author        = {Author, B.},
  journal       = {Journal},
  title         = {Title2},
  year          = {2016}
}
@article{c2016,
  author        = {Author, C.},
  journal       = {Journal},
  title         = {Title3},
  year          = {2016},
  z             = {1}
}
\end{filecontents}
\usepackage[datamodel=\jobname]{biblatex}
\DeclareBibliographyDriver{article}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \usebibmacro{author/translator+others}%
  \setunit{\printdelim{nametitledelim}}\newblock
  \usebibmacro{title}%
  \newunit
  \printlist{language}%
  \newunit\newblock
  \usebibmacro{byauthor}%
  \newunit\newblock
  \usebibmacro{bytranslator+others}%
  \newunit\newblock
  \printfield{version}%
  \newunit\newblock
  \usebibmacro{in:}%
  \usebibmacro{journal+issuetitle}%
  \newunit
  \usebibmacro{byeditor+others}%
  \newunit
  \printfield{z}%
  \newunit\newblock
  \iftoggle{bbx:isbn}
    {\printfield{issn}}
    {}%
  \newunit\newblock
  \usebibmacro{doi+eprint+url}%
  \newunit\newblock
  \usebibmacro{addendum+pubstate}%
  \setunit{\bibpagerefpunct}\newblock
  \usebibmacro{pageref}%
  \newunit\newblock
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
  \usebibmacro{finentry}}
\addbibresource{\jobname.bib}
\begin{document}
    \nocite{*}
    \printbibliography
\end{document}

```

**Comment by schoeps** [comment]
Thanks, this fixed my problem! I will move `DeclareDatamodelFields` etc. into a separate file. 👍 The misuse of the note field was just to make the example as short as possible.

I still think that treating `{0}` and `{1}` differently in my original example is a bug but I will not bother you anymore since my problem is solved :)

**Comment by plk** [comment]
I think that is a side-effect of using source-mapping here which one wouldn't do normally - there is no point having a custom field if it is mapped to a normal field anyway right at the beginning of the processing.

**Comment by schoeps** [comment]
I mapped to `usera` which is recommended in the documentation.

**Comment by plk** [comment]
I need to look at that in the docs, since the datamodel generalisations, there is not much point in the user* fields any more.

**Comment by schoeps** [comment]
Agreed, it was how it used to work... anyway, thanks and have a nice day :)
